iiwa:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Effort Position Controllers ---------------------------------------
  EffortJointInterface_J1_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_1

  EffortJointInterface_J2_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_2

  EffortJointInterface_J3_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_3

  EffortJointInterface_J4_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_4

  EffortJointInterface_J5_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_5

  EffortJointInterface_J6_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_6

  EffortJointInterface_J7_controller:
    type: effort_controllers/JointPositionController
    joint: iiwa_joint_7

  # Forward Position Controllers ---------------------------------------
  PositionJointInterface_J1_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_1

  PositionJointInterface_J2_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_2

  PositionJointInterface_J3_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_3

  PositionJointInterface_J4_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_4

  PositionJointInterface_J5_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_5

  PositionJointInterface_J6_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_6

  PositionJointInterface_J7_controller:
    type: position_controllers/JointPositionController
    joint: iiwa_joint_7

  # Forward Velocity Controllers ---------------------------------------
  VelocityJointInterface_J1_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_1

  VelocityJointInterface_J2_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_2

  VelocityJointInterface_J3_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_3

  VelocityJointInterface_J4_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_4

  VelocityJointInterface_J5_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_5

  VelocityJointInterface_J6_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_6

  VelocityJointInterface_J7_controller:
    type: velocity_controllers/JointVelocityController
    joint: iiwa_joint_7

  # Trajectory Controllers ---------------------------------------
  #
  # Effort Position Controllers ---------------------------------------
  EffortJointInterface_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7

    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default

  # Forward Position Controllers ---------------------------------------
  PositionJointInterface_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7

    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default

  # Forward Velocity Controllers ---------------------------------------
  VelocityJointInterface_trajectory_controller:
    type: velocity_controllers/JointTrajectoryController
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7

    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default

  gazebo_ros_control/pid_gains:
    iiwa_joint_1: {p: 500, i: 15, d: 30, i_clamp: 30}
    iiwa_joint_2: {p: 100000, i: 300, d: 10, i_clamp: 30}
    iiwa_joint_3: {p: 65, i: 15, d: 10, i_clamp: 30}
    iiwa_joint_4: {p: 31, i: 12, d: 7, i_clamp: 30}
    iiwa_joint_5: {p: 23, i: 5, d: 3, i_clamp: 30}
    iiwa_joint_6: {p: 1000, i: 0, d: 0, i_clamp: 30}
    iiwa_joint_7: {p: 12, i: 0.01, d: 0.1, i_clamp: 10}
