<?xml version="1.0" ?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro" >
  <xacro:property name="width" value="640" />
  <xacro:property name="height" value="480" />
  <xacro:property name="length" value="0.02" />
  <xacro:property name="camera_name" value="rpi" />

  <xacro:macro name="rpi" params="parent *origin">
    <!--movable camera-->
    <joint name="joint_${camera_name}" type="fixed">
      <xacro:insert_block name="origin"/>
      <parent link="${parent}"/>
      <child link="link_${camera_name}"/>
    </joint>
    <link name="link_${camera_name}">
      <collision>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${length} ${length}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="0 0 ${length/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${length} ${length}"/>
        </geometry>
      </visual>
      <inertial>
        <mass value="1e-5" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
      </inertial>
    </link>

    <gazebo reference="link_${camera_name}">
      <material>Gazebo/Red</material>
      <sensor type="camera" name="${camera_name}">
        <update_rate>30.0</update_rate>
        <camera name="head">
          <horizontal_fov>1.3962634</horizontal_fov>
          <image>
            <width>${width}</width>
            <height>${height}</height>
            <format>R8G8B8</format>
          </image>
          <clip>
            <near>0.001</near>
            <far>300</far>
          </clip>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.007</stddev>
          </noise>
        </camera>
        <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>0.0</updateRate>
          <cameraName>${camera_name}</cameraName>
          <imageTopicName>image</imageTopicName>
          <cameraInfoTopicName>image_info</cameraInfoTopicName>
          <frameName>${camera_name}</frameName>
          <hackBaseline>0.07</hackBaseline>
          <distortionK1>0.0</distortionK1>
          <distortionK2>0.0</distortionK2>
          <distortionK3>0.0</distortionK3>
          <distortionT1>0.0</distortionT1>
          <distortionT2>0.0</distortionT2>
        </plugin>
      </sensor>
    </gazebo>

  </xacro:macro>

</robot>
